package SensitiveWords;

import com.mayabot.mynlp.fasttext.FastText;
import com.mayabot.mynlp.fasttext.ModelName;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

/**
 * @创建用户: 阿宇
 * @创建时间: 2019/4/22 09:55
 * @类描述:
 */
public class Test {
    public static void main(String[] args) throws Exception {
        String str = "<p>The Indian television has today become a big business, with its popularity graph reaching as high as that of Bollywood.&nbsp;But, in every race, there is a winner and that makes life interesting.&nbsp;There are lots of actresses to choose from, but these great stars made it to the top. Check out these&nbsp;<strong>top&nbsp;5 most beautiful Indian TV serial actresses in 2018.&nbsp;</strong>Without further delay, let us look at our number&nbsp;5 in the list.</p><p><strong>5. Jennifer Winget</strong></p><p class=\"ql-align-center\"><img src=\"http://hl-img.peco.uodoo.com/hubble/app/sm/3b5138e2b127510824fcb617723e5e19.jpg;,70,JPEGX;3,690x\"></p><p class=\"ql-align-center\"><em style=\"color: rgb(155, 155, 155);\">Third party image reference</em></p><p>Indian actress Jennifer Winget was born on May 30, 1985. Winget started her career when she was 12 years old as a child star in the film Raja Jo Rani Se Pyar Ho Gaya and another film on the same role for the movie Kuch Naa Kaho at the age of 14. Likewise, Eastern Eye listed her at the 21st position on the World’s Sexiest Asian Women for 2012.</p><p><strong>4. Surbhi Jyoti</strong></p><p class=\"ql-align-center\"><img src=\"http://hl-img.peco.uodoo.com/hubble/app/sm/983a9ab1c4ddea0914161c3402609bd5.jpg;,70,JPEGX;3,690x\"></p><p class=\"ql-align-center\"><em style=\"color: rgb(155, 155, 155);\">Third party image reference</em></p><p>Surbhi Jyoti is another pretty face on the Indian TV, with her lead role in the Zee TV serial “Qubool Hai”. Her attractive face and captivating eyes have won her huge fan following.</p><p><strong>3. Hina Khan</strong></p><p class=\"ql-align-center\"><img src=\"http://hl-img.peco.uodoo.com/hubble/app/sm/26e50e33601ef2b904cd7ea849f5c810.jpg;,70,JPEGX;3,690x\"></p><p class=\"ql-align-center\"><em style=\"color: rgb(155, 155, 155);\">Third party image reference</em></p><p>Bigg Boss 11 finalist&nbsp;Hina Khan&nbsp;first rose to fame with the longest running soap on Indian Television Yeh Rishta Kya Kehlata Hai, where she played the character of Akshara. Post Yeh Rishta, the actress participated in adventure-based reality show, Khatron Ke Khiladi.</p><p><strong>2.&nbsp;Surbhi Chandana</strong></p><p class=\"ql-align-center\"><img src=\"http://hl-img.peco.uodoo.com/hubble/app/sm/71e6c1780ec5cf2fd287ddc93b915133.webp;,70,JPEGX;3,690x\"></p><p class=\"ql-align-center\"><em style=\"color: rgb(155, 155, 155);\">Third party image reference</em></p><p>Surbhi Chandana aka Annika has flattered us not only by her chemistry with Nakuul Mehta aka Shivay Singh Oberoi but has also given us some cool slangs like Tadi, Michmichi, Raita Fail Gaya, Khidki Tod Idea.</p><p><strong>1.&nbsp;Mouni Roy</strong></p><p class=\"ql-align-center\"><img src=\"http://hl-img.peco.uodoo.com/hubble/app/sm/92e7b1b452830fe562bcaf1286532b54.jpg;,70,JPEGX;3,690x\"></p><p class=\"ql-align-center\"><em style=\"color: rgb(155, 155, 155);\">Third party image reference</em></p><p><br></p>";
        String str2 = "<p>भारतीय टीम ने डबलिन में खेले गए पहले टी20 मैच में आयरलैंड को 75 रन से हराकर 2 टी20 मैचों की सीरीज़ में 1-0 कई बढ़त बना ली थी।</p><p><img src=\"http://img.masala-sg.goldenmob.com/img/ad3b7c307b5a11e8bb52276dc18785f6/271f7cbd8663abd573fc0f551b7521d6-480.jpg\"></p><p><strong>डबलिन:&nbsp;</strong>आज भारत और आयरलैंड के बीच डबलिन में दो टी-20 मैचों की सीरीज का दूसरा T20 मैच खेला जाएगा। भारतीय टीम बुधवार को खेले गए पहले टी-20 मैच को जीत कर इस श्रंखला में एक सोने की बढ़त बनाए हुए हैं और आज होने वाले दूसरे टी20 मैच को भी जीतकर भारतीय टीम इस सीरीज को 2-0 से अपने नाम करना चहेगी।</p><p>भारतीय टीम को अगले सप्ताह से इंग्लैंड के मुश्किल दौरे पर क्रिकेट खेलना है। लेकिन इंग्लैंड दौरे से पहले आज भारतीय टीम आयरलैंड को हराकर इस टी20 सीरीज को 2-0 से जीत होती है तो निश्चित रुप से भारतीय टीम के खिलाड़ियों का मनोबल बढ़ेगा।</p><p><strong>पिच रिपोर्ट और मौसम</strong></p><p>आज डबलिन में सुबह से ही धूप खिली रहेगी और आज डबलिन का औसत तापमान 14°C रहने की उम्मीद है।</p><p><strong>भारतीय प्लेइंग इलेवन में हो सकता है बदलाव</strong></p><p>बुधवार को खेले गए पहले टी-20 मैच में जीत के बाद प्रेस कॉन्फ्रेंस में कप्तान कोहली ने कहा था कि वह दूसरे T20 मैच में भारतीय टीम में जरूर बदलाव करना चाहेंगे। विराट कोहली के इस बयान के लिहाज से देखा जाए तो दूसरे टी-20 मैच में भारतीय टीम के प्लेइंग इलेवन में बदलाव हो सकता है।</p><p>यह भी पढ़े</p><p>अंतर्राष्ट्रीय टी-20 क्रिकेट में एक पारी में सर्वाधिक 200 रन बनाने वाली टीमें,…</p><p><strong>केएल राहुल को मिल सकती है भारतीय टीम में जगह</strong></p><p><img src=\"http://img.masala-sg.goldenmob.com/img/ad3b7c307b5a11e8bb52276dc18785f6/da9b97f9d6d938845a1fbd763d2fe4f6-480.jpg\"><em>Photo Source: BCCI</em></p><p>आज होने वाले दूसरे टी-20 मैच में IPL में शानदार प्रदर्शन करने वाले लोकेश राहुल को भारतीय प्लेइंग इलेवन में जगह मिल सकती है। पहले टी-20 मैच में सभी भारतीय खिलाड़ियों का प्रदर्शन आशा के अनुरूप ही रहा था। लेकिन इसके बावजूद दूसरे T20 मैच में सुरेश रैना या मनीष पांडे की जगह केएल राहुल को टीम में जगह मिल सकती है।</p><p><strong>एक बार फिर स्पिन पर रहेगा दारोमदार</strong></p><p><img src=\"http://img.masala-sg.goldenmob.com/img/ad3b7c307b5a11e8bb52276dc18785f6/4f95b51ee2f2a8c855daec550672a230-480.jpg\"><em>Photo Source: BCCI</em></p><p>आयरलैंड के खिलाफ पहले टी-20 मैच भारतीय टीम के स्पिन गेंदबाज कुलदीप यादव और युजवेंद्र चहल गेंदबाजी की थी और इन दोनों ने मिलकर कुल 7 विकेट्स लिए थे। आज होने वाले दूसरे टी20 मैच में भी इन दोनों स्पिन गेंदबाजो से प्रदर्शन दोहराने की उम्मीद होगी।</p><p><strong>भारतीय टीम की संभावित प्लेइंग इलेवन:&nbsp;</strong>विराट कोहली, रोहित शर्मा, शिखर धवन, सुरेश रैना, महेंद्र सिंह धोनी, हार्दिक पांड्या, मनीष पांडे/केएल राहुल, यजुवेंद्र चहल, कुलदीप यादव, भुवनेश्वर कुमार और जसप्रीत बुमराह।</p>";
        String str3 = "<html><head></head><body><p>Hello friends, welcome to our channel, if you like the news, do not forget to like and follow.</p><p>Friends, today we will introduce you to an actress of South.</p><p><img src=\"http://img.masala-sg.goldenmob.com/img/0b0dbfa909da4313839a3b698ad9c4ba/c947502b55d5b928cd42c2cf3d454d09-480.webp\"></p><p>So friends, what is the beauty of this actress, let's see these pictures.</p><p>Friends, the name of this beautiful actress is Suhani Kalita and her age is just 27 years old but seeing her beauty everyone is surprised because she is very beautiful and hot to look.</p><p><img src=\"http://img.masala-sg.goldenmob.com/img/0b0dbfa909da4313839a3b698ad9c4ba/0c799fea801808b752194550baa20ae4-480.webp\"></p><p>The actress was born in Hyderabad on December 25, 1991, and she started her film career in 1996 as a child artist. And till date, she has worked in many South Hindi and Tamil films and has given many awards to her names.</p><p><img src=\"http://img.masala-sg.goldenmob.com/img/0b0dbfa909da4313839a3b698ad9c4ba/5527394bdb3676a8c52315115177f42b-480.webp\"></p><p>Due to her attractive figure and beauty, Suhani is very fond of social media and keeps sharing the hot pictures there. Where she has made fan followings in her thousands and people like her photographs very much.</p></body></html>\n";

        String par = str2.replaceAll("<.*?>|\\&\\w+|;|\n|\r","");
//        System.out.println(par);
        System.out.println(URLEncoder.encode(par,"UTF8"));

//        FastText fastText = FastText.train(new File("dir/sexwords.txt"), ModelName.sg);
//
//        FastText quantizerFastText = FastText.quantize(fastText,2,false);
//
//        System.out.println(quantizerFastText);


    }
}
